### PR TITLE
version: post-release version bump

### PR DESCRIPTION
**Pull request by Panos512**
Signed-off-by: Panos Paparrigopoulos panos.paparrigopoulos@cern.ch

### CODE REVIEW

**Comment by jirikuncar** [comment]
@Panos512 this PR is premature and should be done after release.

**Comment by Panos512** [comment]
@jirikuncar so I wait for #17 to be merged and `invenio-orcid` to be released and then I rebase this PR?

**Comment by jirikuncar** [comment]
Usually the person who makes the release creates the PR after everything is correctly up on PyPI, RTD, etc.

**Comment by Panos512** [comment]
@jirikuncar Ok great! So you will take care of it?

**Pull request merged**
