### PR TITLE
search: adds ORCID search endpoint

### PR DESCRIPTION
**Pull request by eamonnmag**
- NEW Adds search endpoint for ORCID. Search by
  name, or ORCID iD and retrieve the matching profiles.

### CODE REVIEW

**Comment by jirikuncar** [comment]
@eamonnmag did you talk with @kaplun about a strategy for this package? There is an initial port #1 waiting for integration.

**Comment by eamonnmag** [comment]
Nope. We had a use case to use an endpoint to search for a users name and get back a list of ORCID profile matches (e.g. for the record editor).  So I wrote this quickly to enable it. @kaplun is on holidays, but we should just get these things merged in and have this repo as the main orcid endpoint for installations.

**Comment by Panos512** [comment]
I think we can close this since https://github.com/ORCID/python-orcid already does the job. 

Sorry @eamonnmag 😿

**Comment by eamonnmag** [comment]
awwwww

**Comment by jirikuncar** [comment]
@eamonnmag ✌️

**Pull request closed without merging**
